controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\CanvasController::index

uploadFile:
    path: /upload
    controller: App\Controller\CanvasController::upload
    methods: [GET, POST]

downloadFile:
    path :  /download
    controller: App\Controller\CanvasController::downloadFile
